-- ============================================
-- VITE & GOURMAND - Point d'entrée SQL (obsolète)
-- ============================================
-- Ce fichier est conservé pour référence historique.
-- Utiliser à la place :
--   1. sql/schema.sql        → schéma complet + données de référence
--   2. sql/seed_admin.sql    → compte administrateur (à créer depuis seed_admin.sql.example)
-- ============================================
